### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Mohammad-irr** [HindyDS/RecurrsiveFeatureSelector#1]
Hello HindyDS
Thanks for your great job
1- I have got this error: AttributeError: 'ForwardStepwiseFeatureSelection' object has no attribute 'trial'
what's the solution?

2- I want to cite this methodology and package in my paper, have you a relevance or appropriate paper or document of yours?

Thank you in advance

**Comment by yuenshingyan** [comment]
Hello MohammadSoltani100,

I actually changed the code a while ago. 

Please try the following code instead:

    fsfs= ForwardStepwiseFeatureSelection()
    fsfs.fit(X_train, y_train)
    fsfs.search(estimators, cv=3, scoring='accuracy', verbose=1, tolerance=3)

As for citation, this package was inspired by _A Practical Guide to Dimensionality Reduction by Vishal Patel October 8, 2016_. I personally did not make any actual documentation for this package. 

Besides, I would like to remind you that step wise feature selection is not appropriate to deal time series data yet and I do intend to add new features to address this. Please be careful for it's pros and cons.

**Comment by Mohammad-irr** [comment]
Thank you for your kindly response.
Thank you again for your contribution.
Best regards.
